[package]
name = "practice_01"
version = "0.1.0"
authors = ["Huy Hoàng Phan <hoangph271@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
